Homework 4 sparse matrix
PolinaSavelyeva/ProgrammingHomeworkFs pull request #13
Opened 2022-11-14 20:10 UTC by PolinaSavelyeva

2022-11-15 06:29 UTC, gsvgit requested changes

2022-11-15 06:29 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MatrixMultiplication.fs
> +        | BinTree.Leaf (z), BinTree.Node (x, y) -> fPlus <| BinTree.Node(x, y) <| BinTree.Node(BinTree.Leaf(z), BinTree.Leaf(z))
Можно попробовать меньше новых узлов конструировать.

2022-11-15 06:29 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MatrixMultiplication.fs
> +        | BinTree.None, BinTree.Node (x, y) -> fPlus <| BinTree.Node(x, y) <| BinTree.Node(BinTree.None, BinTree.None)
И здесь тоже.

2022-11-15 06:29 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MatrixMultiplication.fs
> +    let rec fPlus a b =
А как Вы боретесь с тем, что могут получиться деревья из None-ов?

2022-11-15 06:29 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MatrixMultiplication.fs
> +        | BinTree.Leaf (a), QuadTree.Node (first, second, third, fourth) ->
Зачем разбирать дерево, потом снова его собирать. Лишние операции. Попробуйте без этого.

2022-11-15 06:29 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MatrixMultiplication.fs
> +    let rec multiTrees binTree quadTree =
И тут тоже не осень понятно, как обрабатываются поддеревья из None-ов.

2022-11-15 06:29 UTC, gsvgit commented on src/ProgrammingHomeworkFs/SparseMatrix.fs
> +let takeElementOfMatrix i j (matrix: Matrix<'value>) =
Можно сделать красивее: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/members/indexed-properties

2022-11-15 06:29 UTC, gsvgit commented on src/ProgrammingHomeworkFs/SparseVector.fs
> +        val Memory: array<Option<'value>>
А почему в QuadTree Вы не указватете, что значение Option, а тут указываете?

2022-11-15 06:29 UTC, gsvgit commented on src/ProgrammingHomeworkFs/SparseVector.fs
> +let takeElementOfVector i (vector: Vector<'value>) =
Ну и как в матрицах. Можно красивее это оформить.

2022-11-15 06:29 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/SparseMatrixVector.fs
> +        testList
Чот на операции маловато тестов. Сделайте честный тест через сравнение с наивным умножением плотных структур.

2022-11-23 21:00 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/SparseVector.fs
> +        val Memory: array<Option<'value>>
?
https://github.com/PolinaSavelyeva/ProgrammingHomeworkFs/blob/c7fda64c1c0aefb498dfeef624ec823db5da127b/src/ProgrammingHomeworkFs/SparseMatrix.fs#L23

2022-11-25 08:48 UTC, gsvgit commented on src/ProgrammingHomeworkFs/SparseVector.fs
> +        val Memory: array<Option<'value>>
Да, что-то пропустил. А зачем стить типовых аннотаций разный?

2022-11-25 08:51 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MatrixMultiplication.fs
> +        | BinTree.Leaf x, BinTree.Leaf y -> BinTree.Leaf(plusOperation x y)
То есть получается,  что я никогда не могу получить "ноль" в качестве результата?

2022-11-26 06:28 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MatrixMultiplication.fs
> +        | BinTree.Node (x, y), BinTree.Node (z, w) -> BinTree.Node(fPlus x z, fPlus y w)
Если x+z и y+w полоучились None, то получается нередуцированное дерево.

2022-11-26 06:28 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MatrixMultiplication.fs
> +        | BinTree.Node (x, y), BinTree.Node (z, w) -> BinTree.Node(fPlus x z, fPlus y w)
Я бы отдельно неписал уже тест, которые проверяет свойство, что нету поддеревьев из None-ов.

2022-11-26 06:28 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MatrixMultiplication.fs
> +    let rec fPlus a b =
Да и почему бы поэлементную операцию над векторами не вынести в вектора?

2022-11-26 11:16 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/SparseMatrixVector.fs
> +                      let mutable flag = true
Задача на сообразительность: переписать без использования изменяемого флага.

2022-11-28 08:09 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/SparseMatrixVector.fs
> +                      | BinTree.Node (BinTree.None, BinTree.None) -> 0
А почему булева по смыслу функция возвращает инт?

2022-11-29 05:32 UTC, gsvgit approved these changes

2022-11-29 12:57 UTC, merged