Homework 6 experiments
PolinaSavelyeva/ProgrammingHomeworkFs pull request #19
Opened 2023-02-14 22:41 UTC by PolinaSavelyeva

2023-02-15 05:31 UTC, gsvgit requested changes
По результатам замеров кажется, что с параллельностью что-то не так. Либо эксперименты странно поставлены.

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    | Option.Some a, Option.Some b -> Option.Some(a + b)
На то, что в результате может быть 0, специально не проверяете?

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    member val Level = 0u with get, set
А что не подряд с 0 до 4 с шагом 1 ?

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    [<Params(2_500_000u)>]
Можно сразу разных длинн.

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +        vector1 <- SparseVector.Vector(Array.init (Converters.toInt this.Length) (fun _ -> Some(random.Next())))
То есть на самом деле вектора всегда плотные будут?

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    [<Params(3000u)>]
Те же вопросы про уровеь, размеры входа и плотность входных данных.  Хотя, конечно, на плотных тоже интересно. Как и для сложения.

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +        else if array[0][0] <> '%' then
Бывает `elif`.

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +            commentsCutter array[1..]
Кажется, можно просто [Seq.skipWhile](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-seqmodule.html#skipWhile) использовать.

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +                "Incorrect file was given. Expected MatrixMarket format file.\n
Эм... Не понял, что тут должно быть.

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +        if Array.tryHead array = Option.None then
А почему не просто проверка длины на 0?

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +        if zeroArrayLine.Length <> 5 then
Судя по использованию, `zeroArrayLine` надо как-то вменяемее назвать. Что она деалет на самом деле?

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +    let cutArray = commentsCutter array
Это не `cutArray`, это данные без комментариев.

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +    let zeroCutArrayLine =
Опять не понятно, что за функция.

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +    member this.Array = array
А кто такой этот `Array`?

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +    member this.Weight = weight
Вес кого?

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +    let rec listOfDoubleFormation (array: array<string>) =
Ой, куча дублирования кода!

2023-02-15 05:31 UTC, gsvgit commented on src/ProgrammingHomeworkFs/ParallelMatrixAndVectorOperations.fs
> +let vectorAddition level (plusOperation: 'Value1 option -> 'Value2 option -> 'Value3 option) (vector1: Vector<'Value1>) (vector2: Vector<'Value2>) : Vector<'Value3> =
А правда ли, что с уровнем 0 должна полуаться в точности последовательная версия? Можно ли избежать дублирования кода?

2023-02-15 05:31 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/ParallelOperations.fs
> +            [ testProperty "ParallelVectorAddition property test"
Название прям огонь! Что на самом деле тестируется?

2023-02-15 14:08 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    | Option.Some a, Option.Some b -> Option.Some(a + b)
Не, я просто уточнить. Если это осознанно, то ок. А то просто можно слодить два инта, получить 0 и решить, что мы его хранить не хотим.

2023-02-15 14:10 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    | Option.Some a, Option.Some b -> Option.Some(a + b)
Можно конечно сделать, чтобы например Some(1) + Some(-1) -> None, но я пока не знаю зачем, кроме как чтобы матрицы на выходе получались более разреженные?

2023-02-15 14:12 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    | Option.Some a, Option.Some b -> Option.Some(a + b)
Ну, у нас вся эта деетельность как раз для того, чтобы матрицы разреженными были) Но, ещё раз, сейчас это дейстительно не так и важно.

2023-02-15 16:29 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +    let rec listOfDoubleFormation (array: array<string>) =
А без этого или дублирования функций я не знаю как сделать

2023-02-20 05:43 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkDotNet.Artifacts/results/BenchmarkExperiments.MultiplicationBenchmark-report-github.md
> +``` ini
Странно, что с умножением всё так плохо, если я правильно цифры пнимаю. Лишняя параллельность в сложении затесалась?

2023-02-20 05:43 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +        multiplication <| 0u <| IntPlusOperation <| IntMultiOperation <| vector <| matrix
Кажется, тут обратный пайп не нужен. И чуть ниже тоже.

2023-02-20 05:43 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +    let rec generalListFormation (sequence: seq<string>) =
Ох мне эти Вашт `Formatuion`.  Странная калька с русского?

2023-02-20 05:43 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +            (vertexOne, vertexTwo, weight) :: (generalListFormation <| Seq.removeAt 0 sequence)
Кажется, вместо ркописной рекурсивной функции тут можно прото map использовать.

2023-02-20 06:08 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/BenchmarkDotNet.Artifacts/results/BenchmarkExperiments.MultiplicationBenchmark-report-github.md
> +``` ini
Да

2023-02-20 06:08 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +    let rec generalListFormation (sequence: seq<string>) =
:((

2023-02-20 06:10 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkDotNet.Artifacts/results/BenchmarkExperiments.MultiplicationBenchmark-report-github.md
> +``` ini
Надо это как-то починить, чтобы лишнего ничего не было и нормально работало.

2023-02-21 06:03 UTC, gsvgit reviewed
Мне кажется, или умножению стало сильно хуже?

2023-02-21 06:03 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkDotNet.Artifacts/results/BenchmarkExperiments.MultiplicationBenchmark-report-github.md
> +| ParallelMultiplication |    1500 |    2500 |                  2 |                1 |           10 |  4,207.1 ms |  82.86 ms | 131.42 ms |  4,212.1 ms | 14.77 |    0.39 |
Это как оно во столько раз медленнее?

2023-02-21 06:03 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    member val DensityLevel = 0u with get, set
А в чём разреженность измеряется?

2023-02-21 15:48 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/BenchmarkDotNet.Artifacts/results/BenchmarkExperiments.MultiplicationBenchmark-report-github.md
> +| ParallelMultiplication |    1500 |    2500 |                  2 |                1 |           10 |  4,207.1 ms |  82.86 ms | 131.42 ms |  4,212.1 ms | 14.77 |    0.39 |
В этот раз получилось опустить даже до 0.74

2023-02-21 15:50 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    member val DensityLevel = 0u with get, set
Вообще можно разреженность и отрицательными целыми числами задавать, но в таком случае уровни 1 и -1 будут означать обе плотные матрицы, поэтому для однозначности тут uint

2023-02-22 05:16 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    member val DensityLevel = 0u with get, set
Я про то, что эти цифры значат. Процент ненулей, что-то ещё?

2023-02-22 05:18 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkDotNet.Artifacts/results/BenchmarkExperiments.MultiplicationBenchmark-report-github.md
> +| ParallelMultiplication |    1500 |    2500 |                  2 |                1 |           10 |  4,207.1 ms |  82.86 ms | 131.42 ms |  4,212.1 ms | 14.77 |    0.39 |
А. Логично.

Ну, ещё немного и будет в 2 раза быстрее)

2023-02-22 12:19 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/BenchmarkExperiments.fs
> +    member val DensityLevel = 0u with get, set
Каждый 1ый, 5ый, 10ый и тд элемент матрицы ненулевой. (100%, 20%, 10% ненулевых элементов соответсвенно)

2023-02-22 16:32 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/BenchmarkDotNet.Artifacts/results/BenchmarkExperiments.MultiplicationBenchmark-report-github.md
> +| ParallelMultiplication |    1500 |    2500 |                  2 |                1 |           10 |  4,207.1 ms |  82.86 ms | 131.42 ms |  4,212.1 ms | 14.77 |    0.39 |
Получилось, но не на том устройстве, где нужно)
![photo_2023-02-22 19 31 30](https://user-images.githubusercontent.com/113545874/220693355-ebe381c4-67d1-4640-ac1f-4c11943e43d9.jpeg)

2023-02-22 16:38 UTC, gsvgit commented on src/ProgrammingHomeworkFs/BenchmarkDotNet.Artifacts/results/BenchmarkExperiments.MultiplicationBenchmark-report-github.md
> +| ParallelMultiplication |    1500 |    2500 |                  2 |                1 |           10 |  4,207.1 ms |  82.86 ms | 131.42 ms |  4,212.1 ms | 14.77 |    0.39 |
Ну вот интересно, а что мешает на том, где нужно.

2023-02-22 19:12 UTC, PolinaSavelyeva commented
Различия возникают из-за количества логических ядер: 4 в моем случае и 8 на скриншоте; и из-за различия процессоров, что обсуждалось в беседе. С этой точки зрения, можно разделить умножение на 4 параллельные синхронные задачи, и где `multiLevel` = 1  будет одновременно нагружать 4 потока. С уровнями побольше ситуация будет хуже, так и вышло.

2023-02-23 06:42 UTC, gsvgit commented
> Различия возникают из-за количества логических ядер: 4 в моем случае и 8 на скриншоте; и из-за различия процессоров, что обсуждалось в беседе. С этой точки зрения, можно разделить умножение на 4 параллельные синхронные задачи, где `multiLevel` равный 1 будет одновременно нагружать 4 потока. С уровнями побольше ситуация будет хуже, так и вышло.

Хорошо. А что будет, если взять матрицы существенно бОльшего размера? Но при этом достаточно разреженные? Чтобы не больше 10% значащих элементов.

2023-02-23 06:53 UTC, gsvgit reviewed
Я правильно понимаю, что такой абстракции, как граф, у Вас сейчас в коде нет? То есть просто матрицы везде и всегда гоняются? Просто была подзадача "Научиться строить граф на основе прочитанной матрицы смежности." и мы даже на парах что-то про это обсуждали.

Ну и пока разговоры про особенности данных можно отодвинуть на второй план. Видно, что что-то параллельно работает, а детальнее уже в экспериментах будете смотреть.

2023-02-23 06:53 UTC, gsvgit commented on src/ProgrammingHomeworkFs/MtxReader.fs
> +    let data = seq { yield! System.IO.File.ReadLines pathToFile }
А зачем? `ReadLines` и так последовательность возвращает.

2023-02-24 12:03 UTC, PolinaSavelyeva commented
Что-то странное с абстракцией графа получилось. Можно было сделать наследование от матрицы, но не всё, что есть в ней нужно графу.

2023-02-25 06:48 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Graph.fs
> +    new(adjacencyMatrix, verticesCount) =
А размеры матрицы с количеством вершин никак не связаны?

2023-02-25 06:48 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Graph.fs
> +    new(tripleList, verticesCount) =
Ну и тут тот же вопрос.

2023-02-25 13:44 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Graph.fs
> +    new(adjacencyMatrix, verticesCount) =
length1 = length2 = verticesCount в нашем представлении матриц смежности, но почему нельзя его напрямую обозначить в графе, чтобы потом удобно обращаться?

2023-02-25 13:47 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Graph.fs
> +    new(tripleList, verticesCount) =
Из листа триплетов кажется нельзя точно вывести кол-во вершин

2023-02-25 13:47 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Graph.fs
> +    new(tripleList, verticesCount) =
Или ответ, что выше

2023-02-26 06:00 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Graph.fs
> +    new(adjacencyMatrix, verticesCount) =
Обозначить в смысле явно давать доступ --- да. Передавать в конструктор вместо того, чтобы вычислить --- скорее нет. Заодно в конструкторе можно проверить, что матрица "правильная" (например, что она квадратная)

2023-02-26 06:01 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Graph.fs
> +    new(tripleList, verticesCount) =
Да, из триплетов, пожалуй, сложновато. Если есть вершины без рёбер. Тут я загнул.

2023-02-26 07:45 UTC, gsvgit reviewed
Либо я не понял, что Вы на самом деле хотели сделать, либо что-то жуткое.

2023-02-26 07:45 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Graph.fs
> +    val squareTypeFailWith: unit
Что-то сложное. Зачем так? Почему не оставить поле под вершины а в нужных конструкторах просто проверять квадратность матрицы и либо вычислять кол-во вершин, либо брать из аргументов конструктора?

2023-02-26 07:58 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Graph.fs
> +    val squareTypeFailWith: unit
Для чего в этом способе проверять квадратность для вычисления количества вершин?

2023-02-26 07:58 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Graph.fs
> +    val squareTypeFailWith: unit
Если мы граф строим на матрице смежности, то достаточно проверить, что поступающая матрица квадратная (иначе ошибка), а затем `this.VerticesCount` присвоить  одно из измерений матриц.

2023-02-26 08:07 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Graph.fs
> +    val squareTypeFailWith: unit
Вадратность не "для", но просто заодно. Так-то Вы всё правильно говорите: проверили, что квадратная, если нет -- упали, иначе взяли за кол-во вершин одно из измерений.

2023-02-26 10:12 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Graph.fs
> +          VerticesCount =
А можно ли этот код не дублировать?  На всякий случай: из одних конструкторов можно вызывать другие.

2023-02-26 18:35 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Graph.fs
> +        let adjacencyMatrix = toSparseMatrix converter mtxFile
Ыыыы.... А можно просто 
```
new(mtxFile: MtxFile, converter) =
    let adjacencyMatrix = toSparseMatrix converter mtxFile
    Graph adjacencyMatrix
```
?

И всё

2023-02-26 21:04 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Graph.fs
> +        let adjacencyMatrix = toSparseMatrix converter mtxFile
🥇

2023-02-27 04:19 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Graph.fs
> +        { AdjacencyMatrix = Matrix(tripleList, verticesCount, verticesCount)
Ради единообразия здесь можно было бы поступить так же, как в следующем конструктре. Но это уже не так существенно.

2023-02-27 04:20 UTC, gsvgit approved these changes

2023-02-27 04:21 UTC, gsvgit approved these changes

2023-02-27 22:03 UTC, merged