Homework 1 simple functions
PolinaSavelyeva/ProgrammingHomeworkFs pull request #2
Opened 2022-09-30 00:06 UTC by PolinaSavelyeva

2022-09-30 05:27 UTC, gsvgit requested changes

2022-09-30 05:27 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +            [|
Можно ли не дублировать одинаковые циклы?

2022-09-30 05:27 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +            ans <-
А зачем короткие арифметические выражения в несколько строк записывать?

2022-09-30 05:27 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +let arrays (arr: int array) =
Правда ли, что данную задачу можно решить только для масиива интов?

2022-09-30 05:27 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                let ActualResult =
А почему у Вас в разных файлах разный стиль для имён? Не надо так. Выберете какой-то один и пользуйтесь им везде.

2022-10-02 00:48 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Main.fs
> +            ans <-
Это fantomas форматирует, а без него не билдится

2022-10-03 06:07 UTC, gsvgit requested changes

2022-10-03 06:07 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                    arrays [|
Создали обобщённую функцию, а тесты только на целых числах. Добавьте и другие типы.

2022-10-04 14:47 UTC, PolinaSavelyeva commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                let ActualResult =
Не совсем понимаю, где использую разный стиль имен; то, что ActualResult начинается с заглавных в обеих частях?

2022-10-05 05:32 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                let ActualResult =
```ActualResult``` --- точно такое же имя, как и ```fastExpo```, например. ТЬолько в одном слкчае имя с маленькой, а в другом с большой.

2022-10-05 11:24 UTC, PolinaSavelyeva commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                let ActualResult =
Поняла, исправила

2022-10-06 08:08 UTC, gsvgit approved these changes

2022-10-13 22:41 UTC, merged