Homework 2 types and functions
PolinaSavelyeva/ProgrammingHomeworkFs pull request #4
Opened 2022-10-04 18:49 UTC by PolinaSavelyeva

2022-10-05 05:47 UTC, gsvgit requested changes

2022-10-05 05:47 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                    (quickSort lst) = (bubbleSort lst)
А зачем столько скобок?

2022-10-05 05:47 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +type t5 = int * string * bool * int
А это всё точно в домашке нужно?

2022-10-05 05:47 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +    then
А вот это зачем в домашке?

2022-10-05 05:47 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +let rec rightLst (x: 'value) (lst: MyList<'value>) : MyList<'value> =
Функции ```leftLst``` и ```rightLst``` очень похожи. Можно ли их превратить в одну функцию?

2022-10-05 05:47 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +    | Construct (hd, tl) -> concat (concat (quickSort (leftLst hd tl)) (Construct(hd, Empty))) (quickSort (rightLst hd tl))
Кажется, тут лишний ```concat```. Можно без него.

2022-10-05 05:47 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +let rec lenMyOOPList (lst: IList<'value>) : int =
Почему бы не разделить разные списки в разные файлы с разными пространсвами имён? Тогда не надо будет давать такие ужасные имена функциям.

2022-10-05 05:47 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +        if lst.Tail :? MyOOPEmptyList<'value> then
Что?

2022-10-05 05:47 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +    | _ -> failwith "Incorrect type was given. Expected MyOOPEmptyList<'value> or MyOOPNonEmptyList<'value> types. \n Error in -concatOOP- function."
A incorrect --- это какой?

2022-10-05 05:47 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +let rec leftOOPLst (x: 'value) (lst: IList<'value>) : IList<'value> =
И снова две очень похожие функции

2022-10-05 05:47 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +            concatOOP (concatOOP (quickOOPSort (leftOOPLst lst.Head lst.Tail)) (MyOOPNonEmptyList(lst.Head, MyOOPEmptyList()))) (quickOOPSort (rightOOPLst lst.Head lst.Tail))
И снова лишнияя конкатенация.

2022-10-05 05:47 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                testCase "Tests 1.6"
Названия тестов, конечно, говорящие)

2022-10-05 05:47 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                         "concatOOP MyOOPEmptyList() and MyOOPEmptyList() as same as Empty"
А для OOP списка что не добавили тестов на свойства?

2022-10-05 15:27 UTC, PolinaSavelyeva commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                         "concatOOP MyOOPEmptyList() and MyOOPEmptyList() as same as Empty"
Встроенный генератор почему-то ломается на оопшных типах.  Допустим, если вывести результат работы функции над ооп листом, в консоли появится  что-то типа Int32, но никак не (MyOOPNonEmptyList(..... (...)), поэтому в ооп тестах я  результат привожу к алгебраическому типу и сравниваю с ним же. А вот что делать со встроенным генератором не понятно.

2022-10-05 15:30 UTC, PolinaSavelyeva commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                         "concatOOP MyOOPEmptyList() and MyOOPEmptyList() as same as Empty"
Логично было бы сделать TestProperty сравнив два MyList, используя функцию fromMyOOPListToMyList, но этот вариант не работает

2022-10-05 15:37 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Main.fs
> +    | Construct (hd, tl) -> concat (concat (quickSort (leftLst hd tl)) (Construct(hd, Empty))) (quickSort (rightLst hd tl))
`concat` принимает два значения, а тут три листа. Не совсем понимаю, почему один лишний

2022-10-05 15:50 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Main.fs
> +        if lst.Tail :? MyOOPEmptyList<'value> then
Функция используется, чтобы в сортировке  взять хвост от хвоста:

> MyOOPNonEmptyList(lst.Head, takeOOPTail lst.Tail)

К сожалению lst.Tail.Tail  не работает, пришлось сделать функцию

2022-10-05 15:55 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Main.fs
> +    | _ -> failwith "Incorrect type was given. Expected MyOOPEmptyList<'value> or MyOOPNonEmptyList<'value> types. \n Error in -concatOOP- function."
Любой другой потомок IList, который гипотетически может существовать (у нас не существует, но rider перестраховывается и делает предупреждение об _Incomplete pattern matches on this expression_). Тут конкатенация строго для ооп листов.

2022-10-05 15:58 UTC, PolinaSavelyeva commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                    (quickSort lst) = (bubbleSort lst)
Очередная ошибка, которая таинственным образом испарилась на реквесте. Исправила

2022-10-05 16:01 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Main.fs
> +        if lst.Tail :? MyOOPEmptyList<'value> then
Ака реализация `Cons(hd1, Cons(hd2, tl))` , где `tl`- хвост от хвоста

2022-10-06 05:42 UTC, gsvgit commented on tests/ProgrammingHomeworkFs.Tests/Tests.fs
> +                         "concatOOP MyOOPEmptyList() and MyOOPEmptyList() as same as Empty"
Подсказка. Встроенный генератор умеет генерировать системные списки.

2022-10-06 05:43 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +    | _ -> failwith "Incorrect type was given. Expected MyOOPEmptyList<'value> or MyOOPNonEmptyList<'value> types. \n Error in -concatOOP- function."
Я, скорее, про то, что неплохо бы сообщить, кого именно получили. Но это здорово, что Вы понимаете, что тут происходит.

2022-10-06 05:44 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Main.fs
> +    | Construct (hd, tl) -> concat (concat (quickSort (leftLst hd tl)) (Construct(hd, Empty))) (quickSort (rightLst hd tl))
Угу. Только concat - достаточно дорогая операция. Приклеить один элемент можно дешевле. Если я, конечно, правильно понимаю, что тут происходит.

2022-10-06 05:50 UTC, gsvgit requested changes

2022-10-06 05:50 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +    match lst with
Да, так уже лучше намного. А теперь подумайте над тем, что в qsort Вы два раза вызываете эту функцию
 Стало быть два раза проходите по исходному списку. Можно ли пройти один раз?

2022-10-06 05:50 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +
Что-то тут сервер ругается. И он прав.

2022-10-06 05:50 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Abstraction.fs
> +type t5 = int * string * bool * int
Все ещё какие-то странные функции и типы.

2022-10-06 05:50 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +let rec lenMyList (lst: MyList<'value>) : int =
А зачем отделять объявление типа от функций работы с ним? Логичнее собрать в одном месте тип и функции для него. А в другом месте - другой тип и функции для него.

2022-10-06 07:42 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Abstraction.fs
> +type t5 = int * string * bool * int
Мне хотелось отдельно оставить конспект с занятия, но видимо придется почистить

2022-10-06 07:52 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/Main.fs
> +    | Construct (hd, tl) -> concat (concat (quickSort (leftLst hd tl)) (Construct(hd, Empty))) (quickSort (rightLst hd tl))
Понятно, сделать через Construct. Это было довольно очевидно

2022-10-07 06:17 UTC, gsvgit requested changes

2022-10-07 06:17 UTC, gsvgit commented on .fantomasignore
> +Abstraction.fs
Не надо так. Лучше подкрутить настройки: https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +module AlgebraicType
```AlgebraicType``` --- не очень "говорящее" имя. Лучше, например ```AlgebraicList```. А второй, скажем, ```OOPList```. Или как-то аналогично. а то вообще ничего про списки не сказано.

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +    | Construct (_, Empty) -> 1
Можно ли здесь обойтись двумя вариантами вместо трёх?

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +    | Construct (hd, Empty) -> Construct(hd, Empty)
можно просто ```Construct (hd, Empty) -> lst```

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +let lft (a, _) = a
Для пар есть ```fst``` и ```snd```.

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +let rec newLst (x: 'value) (lst: MyList<'value>) =
Кажется, это назвается ```split```

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +            Construct(hd, lft (newLst x tl)), rgt (newLst x tl)
Вы здесь два раза считаете одно и то же. Не надо так.

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +            lft (newLst x tl), Construct(hd,  rgt (newLst x tl))
И здесь тоже повторные вычисления

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicType.fs
> +        concat (quickSort (lft (newLst hd tl))) (Construct(hd, quickSort (rgt (newLst hd tl))))
Как и тут

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/OopType.fs
> +module OopType
Названия, названия...

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/OopType.fs
> +let rec fromMyOOPListToMyList (lst: IList<'value>) : MyList<'value> =
А зачам в пространстве, которое уже и так говорит нам, что мы в OOP, дублировать OOP?

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/OopType.fs
> +let rec newOOPLst (x: 'value) (lst: IList<'value>) =
Название, повторные вычисления

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/OopType.fs
> +            concatOOP (quickOOPSort (lft (newOOPLst lst.Head lst.Tail))) (MyOOPNonEmptyList(lst.Head, quickOOPSort (rgt (newOOPLst lst.Head lst.Tail))))
Повторные вычисления

2022-10-07 06:17 UTC, gsvgit commented on src/ProgrammingHomeworkFs/OopType.fs
> +                      \n Error in -fromMyOOPListToList- function."
Всё ещё ругонь от сервера.

2022-10-12 05:20 UTC, gsvgit requested changes
Уже почти огонь. Ещё посмотрите, как принято называть функции конвертации в коллекциях. Например в системном List. Там есть конвертация в массив и т.д.

2022-10-12 05:20 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicList.fs
> +let rec oneLine (lst: List<'value>) : List<'value> =
Правда ли, что это одна быть функция верхнего уровня? Почему она не может быть локальной функцией в сортировке?

2022-10-12 05:20 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicList.fs
> +let rec splitLst (x: 'value) (lst: List<'value>) =
1. Тот же вопрос про локальность. 
2. А что здесь оставили в названии какие-то обломки от листа?

2022-10-12 05:20 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicList.fs
> +        let sorted = splitLst x tl
А оно правда уже sorted? Я про название.

2022-10-12 05:20 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicList.fs
> +        let sorted = splitLst hd tl
А оно правда уже sorted?

2022-10-12 05:20 UTC, gsvgit commented on src/ProgrammingHomeworkFs/OopList.fs
> +        if lst.Tail :? EmptyList<'value> then
Кажется, избыточная проверка.

2022-10-12 05:20 UTC, gsvgit commented on src/ProgrammingHomeworkFs/OopList.fs
> +        let sorted = splitLst x lst.Tail
1. Тот же вопрос про локальность. 
2. И про имена тоже.

2022-10-14 19:05 UTC, closed without merging