Homework 3 trees
PolinaSavelyeva/ProgrammingHomeworkFs pull request #9
Opened 2022-10-17 16:00 UTC by PolinaSavelyeva

## Checklist

- [ x ] Описать алгебраический тип, задающий дерево, в котором внутренний узел может иметь произвольное количество сыновей.
- [ x ] Реализовать функцию, которая по дереву находит количество различных элементов, хранящихся в узлах. Использовать рекурсию.
- [ x ] Реализовать функцию, которая по дереву строит список, содержащий все значения из всех узлов. Для списка использовать тип MyList из предыдущей задачи. Использовать рекурсию.

2022-10-17 18:42 UTC, gsvgit requested changes

2022-10-17 18:42 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicList.fs
> +module AlgebraicList
А зачем это тут? Это же про списки.

2022-10-17 18:42 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Tree.fs
> +let rec toList (tree: Tree<'value>) : AlgebraicList.List<'value> =
Посмотрите на эту и предыдущую функции. Они очень похожи. Можно ли их обобщить?

2022-10-17 18:42 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Tree.fs
> +type Tree<'value> = Node of hd: 'value * tl: list<Tree<'value>>
Кажется, hd и tl --- не самые удачные названия для деревьев.

2022-10-17 18:42 UTC, gsvgit commented on src/ProgrammingHomeworkFs/Tree.fs
> +        | Node (hd, []) -> Set.empty.Add hd
Попробуйте использовать HashSet.

2022-10-17 20:05 UTC, PolinaSavelyeva commented on src/ProgrammingHomeworkFs/AlgebraicList.fs
> +module AlgebraicList
То есть я этот файлик использую в третьей задаче, и в любом случае мне нужно будет куда-то деть типы и функции к ним

2022-10-18 05:35 UTC, gsvgit commented on src/ProgrammingHomeworkFs/AlgebraicList.fs
> +module AlgebraicList
Доустим. По идее, надо было просто сперва вмёржить предыдущую домашку. Тогда бы и вопросов не возникло.

2022-10-18 22:28 UTC, closed without merging